apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-maven-settings
data:
  settings.xml: |
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
      <!-- 全局设置 -->
      <profiles>
      <profile>
      <id>nexus</id>
      <repositories>
      <repository>
      <id>nexus</id>
      <url>http://52.130.148.56:8081/repository/maven-public/</url>
      <releases>
      <enabled>true</enabled>
      </releases>
      <snapshots>
      <enabled>true</enabled>
      </snapshots>
      </repository>
      </repositories>
      <pluginRepositories>
      <pluginRepository>
      <id>nexus</id>
      <url>http://52.130.148.56:8081/repository/maven-public/</url>
      <releases>
      <enabled>true</enabled>
      </releases>
      <snapshots>
      <enabled>true</enabled>
      </snapshots>
      </pluginRepository>
      </pluginRepositories>
      </profile>
      <profile>
      <id>aliyun</id>
      <repositories>
      <repository>
      <id>aliyun</id>
      <url>https://maven.aliyun.com/repository/public</url>
      <releases>
      <enabled>true</enabled>
      </releases>
      <snapshots>
      <enabled>true</enabled>
      <updatePolicy>always</updatePolicy>
      </snapshots>
      </repository>
      </repositories>
      </profile>
      </profiles>
      
      <!-- 激活上面定义的 profile -->
      <activeProfiles>
      <activeProfile>nexus</activeProfile>
      <activeProfile>aliyun</activeProfile>
      </activeProfiles>
      
      <servers>
      <server>
      <id>nexus</id>
      <username>admin</username>
      <password>Siemens_nexus_1016</password>
      </server>
      </servers>
      <!-- Maven 中央仓库 -->
      <mirrors>
      <mirror>
      <id>nexus</id>
      <name>siemens la</name>
      <url>http://52.130.148.56:8081/repository/maven-public</url>
      <mirrorOf>central</mirrorOf>
      </mirror>
      <mirror>
      <id>alimaven</id>
      <mirrorOf>central</mirrorOf>
      <name>aliyun maven</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
      </mirror>
      </mirrors>
      </settings>
